language: ruby
rvm:
  - rbx-2
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - ruby-head
  - jruby-9.0.1.0
  - jruby-9.0.3.0
  - jruby-9.0.4.0
  - jruby-head

jdk:
  - oraclejdk8

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head

before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx1024m"
