language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-2
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2
  global:
    - BUNDLE_JOBS=4
before_install:
  # Only use 1 job until Travis fixes the rbx --jobs issue.
  - if [ "$TRAVIS_RUBY_VERSION" == "rbx-2" ] ; then export BUNDLE_JOBS=1 ; fi
install: bundle install --retry=3
